# Site wide configuration

url: "//mc-stan.org"

title:
locale: en_US
description:
logo: stan_logo.png
search: false

# Jekyll configuration  (want pygments highlighter, but not supported)

permalink:   /:categories/:title.html
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Stan Development Team
  avatar: ulam-fermiac.pdf
  email: stan@mc-stan.org
  disqus-shortname:
  twitter: mcmc_stan
  facebook: #username
  github: stan-dev
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics: UA-65151620-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
